pipeline {
    agent none
    stages {
        stage('Build') {
           steps {
            script {
                image = docker.build("myimage", "/home/pi/gitDirectory/SimplePythonWebApp")
                println "Newly generated image, " +image.id
            }
           }
        }

        stage('Start') {
           steps {
            script {
                sh 'docker run -d -p 5000:5000 myimage'
            }
           }
        }

    }
}