pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'docker build -t myimage /home/pi/gitDirectory/SimplePythonWebApp/'
                sh 'docker run -d -p 5000:5000 myimage'
            }
        }
    }
}